# Site settings
name: Cheatsheets
title: Cheatsheets
email:
description: "Quick reference cheatsheets."
baseurl: /cheatsheets
url: "http://yourdomain.com"
username: pmackay

source: ./
# Build settings
markdown: redcarpet
permalinks: pretty

collections:
- topics
